# Generated by Django 4.1.4 on 2022-12-09 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=200, null=True)),
                ('productdescription', models.CharField(max_length=200, null=True)),
                ('category_id', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('user_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_joined', models.DateField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vendor_link', models.URLField(null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriceCompare.category')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=200, null=True)),
                ('created_on', models.DateField(max_length=200, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriceCompare.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriceCompare.users')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriceCompare.users'),
        ),
    ]
